"""Write the LED map as JSON, plain text and a C/C++ header."""

import json
import re


def _led_records(layout, design, origin):
    leds = design.leds if design else []
    refs = [c.ref for c in leds]
    out = []
    for i, (r, c) in enumerate(layout.order):
        x, y = layout.board_xy(r, c, origin)
        rec = {"index": i, "row": r, "col": c, "x_mm": round(x, 4), "y_mm": round(y, 4)}
        if i < len(refs):
            rec["ref"] = refs[i]
            rec["rot_deg"] = round(leds[i].rotation, 3)
        out.append(rec)
    return out


def to_json(layout, cfg, design=None):
    origin = (float(cfg["origin_x"]), float(cfg["origin_y"]))
    data = {
        "generator": "KiCad AutoLED",
        "led_type": cfg["preset"],
        "rows": layout.rows,
        "cols": layout.cols,
        "count": layout.count,
        "pitch_mm": [layout.pitch_x, layout.pitch_y],
        "origin_mm": list(origin),
        "order": cfg["order"],
        "zigzag": cfg["zigzag"],
        "zigzag_rotate": cfg["zigzag_rotate"],
        "start_corner": cfg["start_corner"],
        "mask": layout.cells,
        "index": layout.index,
        "leds": _led_records(layout, design, origin),
    }
    # one matrix row per line keeps the file readable
    text = json.dumps(data, indent=2)
    return re.sub(r"\[\s+(-?[\d.]+(?:,\s+-?[\d.]+)*)\s+\]",
                  lambda m: "[" + ", ".join(m.group(1).split()).replace(",,", ",") + "]", text)


def to_txt(layout, cfg, design=None):
    lines = [
        "# KiCad AutoLED map",
        "# type: %s" % cfg["preset"],
        "# grid: %d rows x %d cols, %d LEDs, pitch %.3f x %.3f mm" % (
            layout.rows, layout.cols, layout.count, layout.pitch_x, layout.pitch_y),
        "# order: %s%s from %s" % (cfg["order"], ", zigzag" if cfg["zigzag"] else "", cfg["start_corner"]),
        "",
        "[mask]  # = LED, . = empty",
    ]
    for row in layout.cells:
        lines.append("".join("#" if v else "." for v in row))
    lines += ["", "[index]  # chain / array index, -1 = empty"]
    width = max(2, len(str(max(layout.count - 1, 0))))
    for row in layout.index:
        lines.append(" ".join(str(v).rjust(width) for v in row))
    lines += ["", "[leds]  # index row col x_mm y_mm ref rot_deg"]
    origin = (float(cfg["origin_x"]), float(cfg["origin_y"]))
    for rec in _led_records(layout, design, origin):
        lines.append("%d %d %d %.4f %.4f %s %s" % (
            rec["index"], rec["row"], rec["col"], rec["x_mm"], rec["y_mm"],
            rec.get("ref", ""), rec.get("rot_deg", "")))
    return "\n".join(lines) + "\n"


def _ctype(max_value, signed=False):
    if signed:
        return "int8_t" if max_value < 128 else "int16_t" if max_value < 32768 else "int32_t"
    return "uint8_t" if max_value < 256 else "uint16_t" if max_value < 65536 else "uint32_t"


def _c_matrix(rows, width):
    body = []
    for row in rows:
        body.append("    {" + ", ".join(str(v).rjust(width) for v in row) + "},")
    return "\n".join(body)


def to_header(layout, cfg, design=None):
    p = re.sub(r"\W", "_", cfg["c_prefix"] or "led").strip("_") or "led"
    P = p.upper()
    guard = "%s_MAP_H" % P
    n = layout.count
    idx_t = _ctype(max(n - 1, 1), signed=True)
    rc_t = _ctype(max(layout.rows, layout.cols))
    iw = len(str(max(n - 1, 0))) + 1
    out = [
        "/* Generated by KiCad AutoLED - LED type: %s */" % cfg["preset"],
        "/* order: %s%s from %s */" % (cfg["order"], ", zigzag" if cfg["zigzag"] else "",
                                       cfg["start_corner"]),
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "#include <stdint.h>",
        "",
        "#define %s_ROWS  %d" % (P, layout.rows),
        "#define %s_COLS  %d" % (P, layout.cols),
        "#define %s_COUNT %d" % (P, n),
        "#define %s_NONE  (-1)" % P,
        "#define %s_ZIGZAG %d  /* 1: every other line of the chain runs backwards */" % (
            P, 1 if cfg["zigzag"] else 0),
        "",
        "/* 1 where an LED exists: %s_mask[row][col] */" % p,
        "static const uint8_t %s_mask[%s_ROWS][%s_COLS] = {" % (p, P, P),
        _c_matrix(layout.cells, 1),
        "};",
        "",
        "/* chain index of the LED at [row][col], %s_NONE if empty */" % P,
        "static const %s %s_index[%s_ROWS][%s_COLS] = {" % (idx_t, p, P, P),
        _c_matrix(layout.index, iw),
        "};",
        "",
        "/* row / column of LED number i */",
        "static const %s %s_row[%s_COUNT] = {%s};" % (
            rc_t, p, P, ", ".join(str(r) for r, _ in layout.order)),
        "static const %s %s_col[%s_COUNT] = {%s};" % (
            rc_t, p, P, ", ".join(str(c) for _, c in layout.order)),
        "",
        "/* chain index at (row, col), or %s_NONE outside the grid / on empty cells */" % P,
        "static inline int %s_at(int row, int col)" % p,
        "{",
        "    if (row < 0 || row >= %s_ROWS || col < 0 || col >= %s_COLS)" % (P, P),
        "        return %s_NONE;" % P,
        "    return %s_index[row][col];" % p,
        "}",
        "",
        "#endif /* %s */" % guard,
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------- cut line

def to_cut_svg(loops):
    """Closed cut-line loops (board mm) as an SVG with real mm units."""
    xs = [x for loop in loops for x, _ in loop]
    ys = [y for loop in loops for _, y in loop]
    x0, y0 = min(xs), min(ys)
    w, h = max(xs) - x0, max(ys) - y0
    paths = []
    for loop in loops:
        d = "M " + " L ".join("%.4f %.4f" % (x - x0, y - y0) for x, y in loop) + " Z"
        paths.append('  <path d="%s"/>' % d)
    return "\n".join([
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<svg xmlns="http://www.w3.org/2000/svg" width="%.4fmm" height="%.4fmm" '
        'viewBox="0 0 %.4f %.4f">' % (w, h, w, h),
        '<g fill="none" stroke="#ff0000" stroke-width="0.1">',
    ] + paths + ["</g>", "</svg>", ""])


def to_cut_dxf(loops):
    """Closed cut-line loops (board mm) as DXF R12 LINE entities, Y up."""
    out = ["0", "SECTION", "2", "HEADER", "9", "$INSUNITS", "70", "4", "0", "ENDSEC",
           "0", "SECTION", "2", "ENTITIES"]
    for loop in loops:
        for (ax, ay), (bx, by) in zip(loop, loop[1:] + loop[:1]):
            out += ["0", "LINE", "8", "CUT",
                    "10", "%.4f" % ax, "20", "%.4f" % -ay, "30", "0",
                    "11", "%.4f" % bx, "21", "%.4f" % -by, "31", "0"]
    out += ["0", "ENDSEC", "0", "EOF", ""]
    return "\n".join(out)
